import "./globals.css";
import { Header } from "./components/Header/Header"; 
import { Footer } from "./components/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>PINDIE — Портал инди-игр от студентов Яндекс Практикума</title>
    <link rel="stylesheet" href="./fonts/fonts.css" />
    <link rel="stylesheet" href="./styles/style.css" />
  </head>
  <body>
   <Header />
    {children}
   <Footer />
  </body>
      </body>
    </html>
  );
}
