import "./globals.css";
import { Header } from "./components/Header/Header"; 
import { Footer } from "./components/Footer/Footer";

export const metadata = {
  title: "PINDIE — Портал инди-игр от студентов Яндекс Практикума",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
  <body>
   <Header />
    {children}
   <Footer />
  
      </body>
    </html>
  );
}
